In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import re



train_file = pd.read_csv('train.csv')


def clean_text(text):
    # Make the text all lower case
    text= text.lower()
    
    # Remove special characters and punctuation
    text = re.sub(r'[^\w\s]', '', text)
    
    # Remove extra white spaces (more than one space)
    text = re.sub(r'\s+', ' ', text)
    
    # Strip leading and trailing white spaces
    text = text.strip()
    
    return text

def clean_location(text):
    # Make the input a string
    text = str(text)
    
    # Make the text all lower case
    text = text.lower()
    
    # Remove special characters except for commas
    text = re.sub(r'[^\w\s,]', '', text)
    
    # Remove extra white spaces (more than one space)
    text = re.sub(r'\s+', ' ', text)
    
    # Strip leading and trailing white spaces
    text = text.strip()
    
    return text


def cleaner(file):
    file["text"] = file["text"].apply(lambda text: clean_text(text))
    file["location"] = file["location"].apply(lambda loc: clean_location(loc))
    return file

train_file = cleaner(train_file)

train_file.head(56)

,id,keyword,location,text,target
0,1,NaN,nan,our deeds are the reason of this earthquake ma...,1
1,4,NaN,nan,forest fire near la ronge sask canada,1
2,5,NaN,nan,all residents asked to shelter in place are be...,1
3,6,NaN,nan,13000 people receive wildfires evacuation orde...,1
4,7,NaN,nan,just got sent this photo from ruby alaska as s...,1
5,8,NaN,nan,rockyfire update california hwy 20 closed in b...,1
6,10,NaN,nan,flood disaster heavy rain causes flash floodin...,1
7,13,NaN,nan,im on top of the hill and i can see a fire in ...,1
8,14,NaN,nan,theres an emergency evacuation happening now i...,1
9,15,NaN,nan,im afraid that the tornado is coming to our area,1
10,16,NaN,nan,three people died from the heat wave so far,1
11,17,NaN,nan,haha south tampa is getting flooded hah wait a...,1
12,18,NaN,nan,raining flooding florida tampabay tampa 18 or ...,1
13,19,NaN,nan,flood in bago myanmar we arrived bago,1
14,20,NaN,nan,damage to school bus on 80 in multi car crash ...,1
15,23,NaN,nan,whats up man,0
16,24,NaN,nan,i love fruits,0
17,25,NaN,nan,summer is lovely,0
18,26,NaN,nan,my car is so fast,0
19,28,NaN,nan,what a goooooooaaaaaal,0
20,31,NaN,nan,this is ridiculous,0
21,32,NaN,nan,london is cool,0
22,33,NaN,nan,love skiing,0
23,34,NaN,nan,what a wonderful day,0
24,36,NaN,nan,looooool,0
25,37,NaN,nan,no wayi cant eat that shit,0
26,38,NaN,nan,was in nyc last week,0
27,39,NaN,nan,love my girlfriend,0
28,40,NaN,nan,cooool,0
29,41,NaN,nan,do you like pasta,0
30,44,NaN,nan,the end,0
31,48,ablaze,birmingham,bbcmtd wholesale markets ablaze httptcolhyxeohy6c,1
32,49,ablaze,est september 2012 bristol,we always try to bring the heavy metal rt http...,0
33,50,ablaze,africa,africanbaze breaking newsnigeria flag set abla...,1
34,52,ablaze,"philadelphia, pa",crying out for more set me ablaze,0
35,53,ablaze,"london, uk",on plus side look at the sky last night it was...,0
36,54,ablaze,pretoria,phdsquares mufc theyve built so much hype arou...,0
37,55,ablaze,world wide,inec office in abia set ablaze httptco3imaomknna,1
38,56,ablaze,nan,barbados bridgetown jamaica ûò two cars set ab...,1
39,57,ablaze,paranaque city,ablaze for you lord d,0
40,59,ablaze,live on webcam,check these out httptcoroi2nsmejj httptco3tj8z...,0
41,61,ablaze,nan,on the outside youre ablaze and alive but your...,0
42,62,ablaze,milky way,had an awesome time visiting the cfc head offi...,0
43,63,ablaze,nan,soooo pumped for ablaze southridgelife,0
44,64,ablaze,nan,i wanted to set chicago ablaze with my preachi...,0
45,65,ablaze,nan,i gained 3 followers in the last week you know...,0
46,66,ablaze,"greensboro,north carolina",how the west was burned thousands of wildfires...,1
47,67,ablaze,nan,building the perfect tracklist to life leave t...,0
48,68,ablaze,live on webcam,check these out httptcoroi2nsmejj httptco3tj8z...,0
49,71,ablaze,england,first night with retainers in its quite weird ...,0
50,73,ablaze,"sheffield township, ohio",deputies man shot before brighton home set abl...,1
51,74,ablaze,india,man wife get six years jail for setting ablaze...,1
52,76,ablaze,barbados,santa cruz ûó head of the st elizabeth police ...,0
53,77,ablaze,anaheim,police arsonist deliberately set black church ...,1
54,78,ablaze,abuja,noches elbestia alexis_sanchez happy to see my...,0
55,79,ablaze,usa,kurds trampling on turkmen flag later set it a...,1